name = "apimogus"
type = "webpack"
zone_id = ""
account_id = "e8243099200fd3071a8fc0cdbb4fcb8d"
route = ""
workers_dev = true
compatibility_date = "2022-03-11"

[build]
command = "yarn && yarn build"
[build.upload]
format = "service-worker"
